development:
  cloud_name: dkcfnb31k
  api_key: 175245154553621
  api_secret: jXZg_-fS5Z6pGU7GJzDaC0VSLsI

# production:
#   cloud_name: dkcfnb31k
#   api_key: 175245154553621
#   api_secret: jXZg_-fS5Z6pGU7GJzDaC0VSLsI